[package]
name = "zstd_salvo"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = { version="0.63.1", features = ["compression", "serve-static"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1.27"
tracing-subscriber = "0.3"
